### ISSUE TITLE
关于封禁列表用户头像加载失败的问题

### ISSUE THREAD

**Issue by lumina37** [n0099/vtop#1]
**问题描述**：封禁列表用户头像无法加载，提示“无法载入图像”。
<img width="676" alt="搜狗截图20220227215130" src="https://user-images.githubusercontent.com/48282276/155885312-43ed0ea9-0cac-447b-b688-bec98b282155.png">
原因：firefox从92.0之后就开始默认阻止在https页面中加载http内容，即混合内容。[参考链接](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)
<img width="670" alt="搜狗截图20220227214858" src="https://user-images.githubusercontent.com/48282276/155885384-6b6c0187-3b37-4df1-81f7-5aad0798f311.png">
**解决方案**：在**core.php:[124]**追加一行代码
`$res = str_replace('http://tb.himg.baidu.com', '//tb.himg.baidu.com', $res);`
以从https源加载头像。

**已解决该问题的案例**：https://www.v-8.top/listUserLog?word=asoul
<img width="909" alt="搜狗截图20220227214819" src="https://user-images.githubusercontent.com/48282276/155885349-af2b73d2-368d-48ad-ad81-d1f5d253126a.png">
**未解决该问题的案例**：https://n0099.net/v8/listUserLog
<img width="897" alt="搜狗截图20220227215728" src="https://user-images.githubusercontent.com/48282276/155885363-643da7fb-629f-4c39-ae10-bc5d23be4b5d.png">

我比较懒就不fork了

**Comment by n0099** [comment]
我记得之前他们html里返回的是https://
